---
- name: install httpd
  yum: name=httpd state=installed

- name: copy httpd-proxy.conf
  template: src=httpd-proxy.conf dest=/etc/httpd/conf.d/
  notify: restart httpd

- name: service
  service: name=httpd state=running enabled=yes
